// Auto-generated. Do not edit!

// (in-package action_demo.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class numberFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.server_current_number = null;
    }
    else {
      if (initObj.hasOwnProperty('server_current_number')) {
        this.server_current_number = initObj.server_current_number
      }
      else {
        this.server_current_number = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type numberFeedback
    // Serialize message field [server_current_number]
    bufferOffset = _serializer.uint32(obj.server_current_number, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type numberFeedback
    let len;
    let data = new numberFeedback(null);
    // Deserialize message field [server_current_number]
    data.server_current_number = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_demo/numberFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '882cf344abca1d94163ebb82f74e1aac';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message(peridoic)
    uint32 server_current_number
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new numberFeedback(null);
    if (msg.server_current_number !== undefined) {
      resolved.server_current_number = msg.server_current_number;
    }
    else {
      resolved.server_current_number = 0
    }

    return resolved;
    }
};

module.exports = numberFeedback;
