// Auto-generated. Do not edit!

// (in-package action_demo.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class numberGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cient_request_number = null;
    }
    else {
      if (initObj.hasOwnProperty('cient_request_number')) {
        this.cient_request_number = initObj.cient_request_number
      }
      else {
        this.cient_request_number = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type numberGoal
    // Serialize message field [cient_request_number]
    bufferOffset = _serializer.uint32(obj.cient_request_number, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type numberGoal
    let len;
    let data = new numberGoal(null);
    // Deserialize message field [cient_request_number]
    data.cient_request_number = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_demo/numberGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '29d9e98facec52d676a3a304a7145e58';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal(once)
    uint32 cient_request_number
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new numberGoal(null);
    if (msg.cient_request_number !== undefined) {
      resolved.cient_request_number = msg.cient_request_number;
    }
    else {
      resolved.cient_request_number = 0
    }

    return resolved;
    }
};

module.exports = numberGoal;
