// Auto-generated. Do not edit!

// (in-package action_demo.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class numberResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.not_used = null;
    }
    else {
      if (initObj.hasOwnProperty('not_used')) {
        this.not_used = initObj.not_used
      }
      else {
        this.not_used = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type numberResult
    // Serialize message field [not_used]
    bufferOffset = _serializer.uint32(obj.not_used, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type numberResult
    let len;
    let data = new numberResult(null);
    // Deserialize message field [not_used]
    data.not_used = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_demo/numberResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6f2872726aa09dd4e01db1566742cd00';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result(once)
    uint32 not_used
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new numberResult(null);
    if (msg.not_used !== undefined) {
      resolved.not_used = msg.not_used;
    }
    else {
      resolved.not_used = 0
    }

    return resolved;
    }
};

module.exports = numberResult;
