(cl:defpackage action_demo-msg
  (:use )
  (:export
   "<NUMBERACTION>"
   "NUMBERACTION"
   "<NUMBERACTIONFEEDBACK>"
   "NUMBERACTIONFEEDBACK"
   "<NUMBERACTIONGOAL>"
   "NUMBERACTIONGOAL"
   "<NUMBERACTIONRESULT>"
   "NUMBERACTIONRESULT"
   "<NUMBERFEEDBACK>"
   "NUMBERFEEDBACK"
   "<NUMBERGOAL>"
   "NUMBERGOAL"
   "<NUMBERRESULT>"
   "NUMBERRESULT"
  ))

