; Auto-generated. Do not edit!


(cl:in-package action_demo-msg)


;//! \htmlinclude numberFeedback.msg.html

(cl:defclass <numberFeedback> (roslisp-msg-protocol:ros-message)
  ((server_current_number
    :reader server_current_number
    :initarg :server_current_number
    :type cl:integer
    :initform 0))
)

(cl:defclass numberFeedback (<numberFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <numberFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'numberFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_demo-msg:<numberFeedback> is deprecated: use action_demo-msg:numberFeedback instead.")))

(cl:ensure-generic-function 'server_current_number-val :lambda-list '(m))
(cl:defmethod server_current_number-val ((m <numberFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_demo-msg:server_current_number-val is deprecated.  Use action_demo-msg:server_current_number instead.")
  (server_current_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <numberFeedback>) ostream)
  "Serializes a message object of type '<numberFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'server_current_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'server_current_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'server_current_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'server_current_number)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <numberFeedback>) istream)
  "Deserializes a message object of type '<numberFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'server_current_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'server_current_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'server_current_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'server_current_number)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<numberFeedback>)))
  "Returns string type for a message object of type '<numberFeedback>"
  "action_demo/numberFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'numberFeedback)))
  "Returns string type for a message object of type 'numberFeedback"
  "action_demo/numberFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<numberFeedback>)))
  "Returns md5sum for a message object of type '<numberFeedback>"
  "882cf344abca1d94163ebb82f74e1aac")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'numberFeedback)))
  "Returns md5sum for a message object of type 'numberFeedback"
  "882cf344abca1d94163ebb82f74e1aac")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<numberFeedback>)))
  "Returns full string definition for message of type '<numberFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message(peridoic)~%uint32 server_current_number~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'numberFeedback)))
  "Returns full string definition for message of type 'numberFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message(peridoic)~%uint32 server_current_number~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <numberFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <numberFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'numberFeedback
    (cl:cons ':server_current_number (server_current_number msg))
))
