; Auto-generated. Do not edit!


(cl:in-package action_demo-msg)


;//! \htmlinclude numberGoal.msg.html

(cl:defclass <numberGoal> (roslisp-msg-protocol:ros-message)
  ((cient_request_number
    :reader cient_request_number
    :initarg :cient_request_number
    :type cl:integer
    :initform 0))
)

(cl:defclass numberGoal (<numberGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <numberGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'numberGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_demo-msg:<numberGoal> is deprecated: use action_demo-msg:numberGoal instead.")))

(cl:ensure-generic-function 'cient_request_number-val :lambda-list '(m))
(cl:defmethod cient_request_number-val ((m <numberGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_demo-msg:cient_request_number-val is deprecated.  Use action_demo-msg:cient_request_number instead.")
  (cient_request_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <numberGoal>) ostream)
  "Serializes a message object of type '<numberGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'cient_request_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'cient_request_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'cient_request_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'cient_request_number)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <numberGoal>) istream)
  "Deserializes a message object of type '<numberGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'cient_request_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'cient_request_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'cient_request_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'cient_request_number)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<numberGoal>)))
  "Returns string type for a message object of type '<numberGoal>"
  "action_demo/numberGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'numberGoal)))
  "Returns string type for a message object of type 'numberGoal"
  "action_demo/numberGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<numberGoal>)))
  "Returns md5sum for a message object of type '<numberGoal>"
  "29d9e98facec52d676a3a304a7145e58")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'numberGoal)))
  "Returns md5sum for a message object of type 'numberGoal"
  "29d9e98facec52d676a3a304a7145e58")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<numberGoal>)))
  "Returns full string definition for message of type '<numberGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal(once)~%uint32 cient_request_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'numberGoal)))
  "Returns full string definition for message of type 'numberGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal(once)~%uint32 cient_request_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <numberGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <numberGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'numberGoal
    (cl:cons ':cient_request_number (cient_request_number msg))
))
