; Auto-generated. Do not edit!


(cl:in-package action_demo-msg)


;//! \htmlinclude numberResult.msg.html

(cl:defclass <numberResult> (roslisp-msg-protocol:ros-message)
  ((not_used
    :reader not_used
    :initarg :not_used
    :type cl:integer
    :initform 0))
)

(cl:defclass numberResult (<numberResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <numberResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'numberResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_demo-msg:<numberResult> is deprecated: use action_demo-msg:numberResult instead.")))

(cl:ensure-generic-function 'not_used-val :lambda-list '(m))
(cl:defmethod not_used-val ((m <numberResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_demo-msg:not_used-val is deprecated.  Use action_demo-msg:not_used instead.")
  (not_used m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <numberResult>) ostream)
  "Serializes a message object of type '<numberResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'not_used)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'not_used)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'not_used)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'not_used)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <numberResult>) istream)
  "Deserializes a message object of type '<numberResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'not_used)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'not_used)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'not_used)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'not_used)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<numberResult>)))
  "Returns string type for a message object of type '<numberResult>"
  "action_demo/numberResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'numberResult)))
  "Returns string type for a message object of type 'numberResult"
  "action_demo/numberResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<numberResult>)))
  "Returns md5sum for a message object of type '<numberResult>"
  "6f2872726aa09dd4e01db1566742cd00")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'numberResult)))
  "Returns md5sum for a message object of type 'numberResult"
  "6f2872726aa09dd4e01db1566742cd00")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<numberResult>)))
  "Returns full string definition for message of type '<numberResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result(once)~%uint32 not_used~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'numberResult)))
  "Returns full string definition for message of type 'numberResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result(once)~%uint32 not_used~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <numberResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <numberResult>))
  "Converts a ROS message object to a list"
  (cl:list 'numberResult
    (cl:cons ':not_used (not_used msg))
))
