// Generated by gencpp from file action_demo/numberResult.msg
// DO NOT EDIT!


#ifndef ACTION_DEMO_MESSAGE_NUMBERRESULT_H
#define ACTION_DEMO_MESSAGE_NUMBERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_demo
{
template <class ContainerAllocator>
struct numberResult_
{
  typedef numberResult_<ContainerAllocator> Type;

  numberResult_()
    : not_used(0)  {
    }
  numberResult_(const ContainerAllocator& _alloc)
    : not_used(0)  {
  (void)_alloc;
    }



   typedef uint32_t _not_used_type;
  _not_used_type not_used;





  typedef boost::shared_ptr< ::action_demo::numberResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_demo::numberResult_<ContainerAllocator> const> ConstPtr;

}; // struct numberResult_

typedef ::action_demo::numberResult_<std::allocator<void> > numberResult;

typedef boost::shared_ptr< ::action_demo::numberResult > numberResultPtr;
typedef boost::shared_ptr< ::action_demo::numberResult const> numberResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_demo::numberResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_demo::numberResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace action_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'action_demo': ['/home/rcui/Desktop/PJ/pj2/devel/share/action_demo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::numberResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::numberResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::numberResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::numberResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::numberResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::numberResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_demo::numberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f2872726aa09dd4e01db1566742cd00";
  }

  static const char* value(const ::action_demo::numberResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f2872726aa09dd4ULL;
  static const uint64_t static_value2 = 0xe01db1566742cd00ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_demo::numberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_demo/numberResult";
  }

  static const char* value(const ::action_demo::numberResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_demo::numberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result(once)\n\
uint32 not_used\n\
";
  }

  static const char* value(const ::action_demo::numberResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_demo::numberResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.not_used);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct numberResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_demo::numberResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_demo::numberResult_<ContainerAllocator>& v)
  {
    s << indent << "not_used: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.not_used);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_DEMO_MESSAGE_NUMBERRESULT_H
